collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5
color:
  saturation: 1
  brandStrength: 0.9787029
  rhythmicContrast: 0.3180443
  brandColors:
    - '#7F7864'
    - '#FFFFFF'
    - '#6D1529'
    - '#15171E'
    - '#306637'
  lightness: 0.9348289
layout_spectrum: 1
name: KidCurrency
